services:
  cryptomataz:
    build:
      context: .  
    container_name: cryptomataz
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      -  ./src:/app/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - cryptomataz-network

networks:
  cryptomataz-network:
    driver: bridge
